### ISSUE TITLE
merge: different behavior of two-way and n-way merge

### ISSUE THREAD

**Issue by tyrasd** [osmcode/osmium-tool#57] opened 2017-05-09 14:08 UTC
I found a subtle difference in how the *merge* command handles two-way and n-way merges. It's possibly a bug that the output of a two-way merge can contain the same version of an object twice, if the inputs have them with differing timestamp metadata.

[This code](https://github.com/osmcode/osmium-tool/commit/d0ddf6905e85456b96409f43a631cd8229bf156b#diff-ac43b5cee0822b42e9984517d896db2bR157) behaves slightly different than the more general n-way merge path, because [set_union](http://en.cppreference.com/w/cpp/algorithm/set_union) uses the `<` operator under the hood, where libosmium takes an object's timestamp also [into account](https://github.com/osmcode/libosmium/blob/master/include/osmium/osm/object.hpp#L466-L483), not like the [`==`](https://github.com/osmcode/libosmium/blob/master/include/osmium/osm/object.hpp#L453-L460) used [below](https://github.com/osmcode/osmium-tool/commit/d0ddf6905e85456b96409f43a631cd8229bf156b#diff-ac43b5cee0822b42e9984517d896db2bR182).

I found this after merging two osh files which contained both the same version of an object with slightly different timestamps (I guess because of a software bug/glitch/bitflip/? during the creation of one of the input files). After reading the [man page](https://github.com/osmcode/osmium-tool/blob/master/man/osmium-merge.md), I expected that only one of these versions should be included in the output, but found both.

**Comment by joto** [comment] 2017-05-09 15:07
Duplicate of #41.

**Comment by tyrasd** [comment] 2017-05-09 15:17
I see… Can you explain why the other ticket was closed? If this is a wontfix, then the explanation on the man page is not fully correct: *While merging only object type, id, and version are compared.* (when in the two-file case the timestamp is also compared).

**Comment by joto** [comment] 2017-05-09 15:33
Not 100% correct, okay. But the important part is: "If you have objects with the same type, id, and version but different other data, the result of this command is undefined." And that clearly says that when you put inconsistent data in you can't expect anything.

**Comment by tyrasd** [comment] 2017-05-09 15:39
OK, right. I've read it in the sense of: it's undefined which of the two objects with the same type/id/version identifier gets into the output.

Wouldn't it be easy to fix, though:

```cpp
bool typeidversion_comparator(const osmium::OSMObject& lhs, const osmium::OSMObject& rhs) {
    return const_tie(lhs.type(), lhs.id(), lhs.version()) <
           const_tie(rhs.type(), rhs.id(), rhs.version());
}

…

std::set_union(…, typeidversion_comparator);
```

This does the trick for me and makes osmium-tool's output consistent across both the two-way and n-way merge cases.

**Comment by joto** [comment] 2017-05-09 16:02
The important part here is: I am not committing to any specific behaviour when you use the command outside the spec. That is important, because it allows me choose any implementation, specifically the implementation which is easiest and fastest for good input. I guess I have to update the man page to make this more clear.

Your fix might work in your case, but not in others. I am not concerned with making something consistent which is outside the expected behaviour anyway.

**Closed** 2017-05-09 17:55 UTC
