### ISSUE TITLE
Osmium time filter with history data

### ISSUE THREAD

**Issue by rsmahabir** [osmcode/osmium-tool#63] opened 2017-08-02 05:50 UTC
Hi,

May be I'm making an error somewhere. I successfully built osmium v1.6.1 from the git repository. However, when I use the filter-time command with both FROM_TIME TO_TIME, the results are not restricted by the FROM_TIME. Therefore, the results containing all history data up to the TO_TIME and not between the FROM_TIME to TO_TIME.

Example Command:
./osmiumv161/build/osmium time-filter -O -o test.osm Antarctica.osh.pbf 2010-01-01T00:00:00Z 2015-01-01T00:00:00Z

Did anyone have a similar issue?

Thanks for your help.

P.S. I'm using Ubuntu LTS 16

**Comment by joto** [comment] 2017-08-02 07:11
I can't reproduce this here. Can you give an example of an object that is in the file that you think should not be in the file?

There is one issue here that might be confusing: The output contains all objects that *were valid somewhere in the time window*. So this includes objects that were created before that time window but haven't been deleted or changed yet before the time window starts. So for instance in your example an object that was created on 2009-01-01 and changed in 2011-01-01 will be in there with both versions, because it was valid in the first version from 2010-01-01 to 2010-12-31 in your time window.

If you want to know all object (versions) created in a given time frame, you can not do this with this command. The easiest way to achieve this with osmium currently is to convert the data to OPL and filter that. Your example would look like this: `osmium cat Antarctica.osh.pbf -f opl | grep ' t201[01234]-' | osmium cat -F opl -o test.osh`. Of course this gets much more complicated if the end dates are not that simple.

**Comment by rsmahabir** [comment] 2017-08-03 06:46
Ahhhhhh....that makes a lot of sense. I'll have a look at the data again, but I bet you are right.

By the way, are you familiar with a CentOS install for Libosmium? I can find packages for Ubuntu, Fedora,... but not CentOS 7. 

Thanks Jochen

**Closed** 2017-08-08 13:29 UTC
