### ISSUE TITLE
osmium extract does not extract antimeridian ways

### ISSUE THREAD

**Issue by rouen-sk** [osmcode/osmium-tool#220] opened 2021-07-12 12:13 UTC
I am trying to make extract of Alaska, using geojson polygon file. 
Process is successful, but in the resulting extract, ways on antimeridian (180/-180 lon) are missing, despite polygon covering that part of antimeridian. 

Example IDs of missing ways: 42394837, 46113981
Interesting thing is that nodes on antimeridian are present in extract (ie. node 529267768)

[polygon_us_alaska.zip](https://github.com/osmcode/osmium-tool/files/6801195/polygon_us_alaska.zip)

**Comment by joto** [comment] 2021-07-14 13:25
The man page says "_Osmium will make sure that all nodes on the vertices of the boundary of the region will be in the extract, but nodes that happen to be directly on the boundary, but between those vertices, might  end up in the extract or not._" So this is somewhat expected behaviour.

The man page goes on to say: "_In almost all cases this will be good enough, but if you want to make really sure you got everything, use a small buffer around your region._" Unfortunately that's not possible in this case because coordinates beyond +/- 180° are invalid, so you can't create such a buffer.

I tried fixing this in #221. Can you check whether that fixes your problem.

**Comment by rouen-sk** [comment] 2021-07-15 08:05
Thank you @joto , I confirm that the build from `fix-point-in-polygon` branch does work in my use case, antimeridian ways are present in resulting extract.

**Comment by watbywbarif** [comment] 2021-07-22 08:29
Not sure if this is related but it could be, tried to extract Alaska state boundary by id:
`osmium getid north-america-latest.osm.pbf r1116270 -r -o Alaska.pbf`

Unable to draw entire polygon in QGis, only few small islands. Same result if using planet.osm.pbf for source.

pbflint reports missing ways, seams like all on Eastern Hemisphere:

> ./pbflint.linux.bin tmp11.pbf
> error: relation 1116270 missing member way 46113982
> error: relation 1116270 missing member way 42394837
> error: relation 1116270 missing member way 42394795
> error: relation 1116270 missing member way 46113981
> error: relation 1116270 missing member way 42394788
> error: relation 1116270 missing member way 42394794
> error: relation 1116270 missing member way 42394790

Tried with `osmium-tool 1.10`, `1.13` and `202def6 - Fix point-in-polygon-check in extract command`, same results.

**Comment by joto** [comment] 2021-07-22 08:36
@watbywbarif No, not related. If you are not sure if an issue is related or not, *open a new issue*.

**Comment by joto** [comment] 2021-07-24 15:12
Merged now.

**Closed by joto** 2021-07-24 15:12 UTC
