### ISSUE TITLE
finland extract missing data?

### ISSUE THREAD

**Issue by karme** [osmcode/osmium-tool#75] opened 2017-09-06 09:49 UTC
i do the following to extract finland (relation 54224):
```
osmium getid -r planet-170821.osm.pbf r54224 -o finland-border.osm --overwrite
osmium extract -p finland-border.osm planet-170821.osm.pbf -o finland.osm
pbzip2 finland.osm
```
and get 44M of data
if i compare this to the geofabrik extract at http://download.geofabrik.de/europe/finland-170831.osm.bz2
with 493M of data I think there is lots of data missing.

**Comment by joto** [comment] 2017-09-06 11:02
Geofabrik uses the [`smart` strategy](http://blog.geofabrik.de/en/?p=397) while the default strategy is `complete_ways`. This explains some difference, but I wouldn't have expected it to be that large. Feel free to investigate this further, but until there is some more evidence I am chalking this up to differences in the parameters or so.

**Comment by karme** [comment] 2017-09-06 11:34
if i look at this way: http://www.openstreetmap.org/way/2288521
(http://nominatim.openstreetmap.org/lookup?osm_ids=W2288521)
this way is clearly in finland. I can find it in the geofabrik extract but not in the osmium extract

**Comment by karme** [comment] 2017-09-06 12:28
if I export a gpx http://ra.osmsurround.org/exportRelation/gpx?relationId=54224 convert it to geojson and use this for the cut the result is as expected. (479M of data and the way 2288521 is included)

**Comment by joto** [comment] 2017-09-06 15:05
I think the problem is that when you cut out the relation with `getid` you get several other relations in the file, too. The man page says what happens then: *If there are several (multi)polygons in a poly file or OSM file, they will be merged. The (multi)polygons must not overlap, otherwise the result is undefined.* In this case there are overlapping relations, so it isn't guaranteed to work properly. Now we can argue, of course, whether Osmium could do better here, but this seems to me to be a case where it keeps to the documented behaviour.

**Comment by joto** [comment] 2017-09-07 07:53
I thought some more about this. Both `osmium getid` and `osmium extract` are doing what they are supposed to do. The problem is that they don't fit together as well as I had thought and my documentation recommends using `osmium getid` which clearly doesn't work in all cases. So we need something better. I am thinking about different solutions now but I am not sure yet what they are.

**Comment by joto** [comment] 2019-10-01 19:53
The `osmium getid` command now has an option `-t`. When this is used, the tags on all objects are removed except on the objects actually requested. So other relations (or closed ways) that happen to be in the file will not matter and not confuse `osmium extract`.

**Closed by joto** 2019-10-01 19:53 UTC
