### ISSUE TITLE
Alaska state boundary extract missing ways on Eastern Hemishpere

### ISSUE THREAD

**Issue by watbywbarif** [osmcode/osmium-tool#222] opened 2021-07-22 08:41 UTC
Tried to extract Alaska state boundary by id:
`osmium getid north-america-latest.osm.pbf r1116270 -r -o Alaska.pbf`

Unable to draw entire polygon in QGis, only few small islands. Same result if using planet.osm.pbf for source. Visually looks like other 50 states extracted OK.

pbflint reports missing ways, seams like all on Eastern Hemisphere:

> ./pbflint.linux.bin Alaska.pbf
> error: relation 1116270 missing member way 46113982
> error: relation 1116270 missing member way 42394837
> error: relation 1116270 missing member way 42394795
> error: relation 1116270 missing member way 46113981
> error: relation 1116270 missing member way 42394788
> error: relation 1116270 missing member way 42394794
> error: relation 1116270 missing member way 42394790

Tried with `osmium-tool 1.10`, `1.13` and `202def6 - Fix point-in-polygon-check in extract command`, same results.

**Comment by joto** [comment] 2021-07-22 09:26
Are the missing ways in the input file in the first place?

**Comment by watbywbarif** [comment] 2021-07-22 11:10
Excellent question that resolved all the mysteries that were bugging me :)

Ways are missing in north-america-latest.osm.pbf but are there in planet-210628.osm.pbf.
But, when I was debugging this the first time few weeks ago I tried to extract relation with `osmium getid` without `-r` argument and incomplete output made me assume that osmium works bad on both america and planet data.

So when I run this `osmium getid  planet-210628.osm.pbf r1116270 -r -o Alaska.pbf` result is valid.

Sorry for invalid report!

**Comment by watbywbarif** [comment] 2021-09-15 11:48
This is tougher than it looked, I have returned to this project and I think that problems that exist in geofabrik export are caused with osmium extract bug.

Alaska indeed looks broken in geofabrik export:
```
osmium getid north-america-latest.osm.pbf r1116270 -r -o alaska-from-na.pbf
./pbflint.linux.bin alaska-from-na.pbf
error: relation 1116270 missing member way 46113982
error: relation 1116270 missing member way 42394837
error: relation 1116270 missing member way 42394795
error: relation 1116270 missing member way 46113981
error: relation 1116270 missing member way 42394788
error: relation 1116270 missing member way 42394794
error: relation 1116270 missing member way 42394790
ErrorCount: 7
WarningCount: 0
TotalNodes: 36584
TotalWays: 121
TotalRelations: 1
```

Then when I switch to planet I get this:
```
osmium getid planet-latest.osm.pbf r1116270 -r -o alaska-from-planet.pbf
./pbflint.linux.bin alaska-from-planet.pbf
ErrorCount: 0
WarningCount: 0
TotalNodes: 40470
TotalWays: 128
TotalRelations: 1

# no problem for now but here gets interesting:

osmium extract --bbox -180,-90,0,90 alaska-from-planet.pbf -o alaska-from-planet-west.pbf
./pbflint.linux.bin alaska-from-planet-west.pbf
error: relation 1116270 missing member way 46113982
error: relation 1116270 missing member way 42394837
error: relation 1116270 missing member way 42394795
error: relation 1116270 missing member way 42394788
error: relation 1116270 missing member way 42394794
error: relation 1116270 missing member way 42394790
ErrorCount: 6
WarningCount: 0
TotalNodes: 36590
TotalWays: 122
TotalRelations: 1
```

Cutting to west hemisphere produces invalid .pbf with missing ways, i will assume if I used [north-america.poly](http://download.geofabrik.de/north-america.poly) I will get same broken Alaska polygon which exists in geofabrik extract. I am also not sure, but I guess geofabrik uses osimum for cutting.

**Comment by joto** [comment] 2021-09-18 13:35
Might be the same problem as #226.

**Comment by joto** [comment] 2021-09-24 14:41
The `poly` file the geofabrik uses (yes, they use `osmium extract`) does not contain the 180° and -180° coordinates, but something like -179.995° or so. So that's a bug in their poly file. Independently of that, there is a bug in osmium which I hopefully fixed in #229. Please try that.

**Comment by watbywbarif** [comment] 2021-09-27 11:50
Tried with latest code, but nothing changed.

I checked executable & pbf date-times, can't see what could I miss. 

Also, I was using ```--bbox -180,-90,0,90``` from the start, so I am not sure if this fix could apply?

**Comment by joto** [comment] 2021-09-27 12:40
@watbywbarif Okay, I am closing this here then. The Geofabrik `poly` file definitely doesn't include the 180° coordinates, so it couldn't work independently of any error that might be or might have been in `osmium extract`. This is really something you'd have to take up with Geofabrik. (I mentioned it to them already so it might get fixed at some point.)

**Closed by joto** 2021-09-27 12:40 UTC

**Comment by watbywbarif** [comment] 2021-09-27 12:46
@joto This has nothing with Geofabrik!

Concentrate on lines here:

Get Alaska relation:
```osmium getid planet-latest.osm.pbf r1116270 -r -o alaska-from-planet.pbf```

Extract with bbox:
```osmium extract --bbox -180,-90,0,90 alaska-from-planet.pbf -o alaska-from-planet-west.pbf```

Bbox cut makes invalid relations, Geofabrik was only one example where same problem got out.

**Comment by joto** [comment] 2021-09-27 13:02
Okay, this got waaay to confusing. Please open a new issue and start from the beginning. Add all commands you are running and describe what exactly the problem is.
